spring:
  application:
    name: tg-admin

server:
  port: 8080
  forward-headers-strategy: native

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
