spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/tg-app?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  liquibase:
    drop-first: false