spring:
  application:
    name: tg-app
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    contexts: faker
    drop-first: true
  h2:
    console:
      enabled: true

---

spring:
  config:
    activate:
      on-profile: stage
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/${DB_NAME:tg-database}?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  liquibase:
    drop-first: false
    contexts: stage

