services:
  tg-app-prod:
    image: feurle/tg-app:latest
    container_name: tg-app-prod
    restart: unless-stopped
    expose:
      - "8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_HOST=tg-database
      - DB_NAME=tg-database
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - MAIL_FROM=${MAIL_FROM}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ACTUATOR_USERNAME=${ACTUATOR_USERNAME}
      - ACTUATOR_PASSWORD=${ACTUATOR_PASSWORD}
      - SERVICE_BASE_URL=http://tg-app-prod:8080
    networks:
      - nginx-proxy-network

  tg-web-prod:
    image: feurle/tg-web:latest
    container_name: tg-web-prod
    restart: unless-stopped
    environment:
      - BACKEND_URL=http://tg-app-prod:8080
      - VIRTUAL_HOST=${VIRTUAL_HOST_PROD}
      - LETSENCRYPT_HOST=${VIRTUAL_HOST_PROD}
    networks:
      - nginx-proxy-network

networks:
  nginx-proxy-network:
    external: true