services:
  tg-app-test:
    image: feurle/tg-app:snapshot
    container_name: tg-app-test
    restart: unless-stopped
    expose:
      - "8080"
    environment:
      - SPRING_PROFILES_ACTIVE=stage
      - DB_HOST=tg-database
      - DB_NAME=tg-database-test
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - MAIL_FROM=${MAIL_FROM}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - SERVICE_BASE_URL=http://tg-app-test:8080
    networks:
      - nginx-proxy-network

  tg-web-test:
    image: feurle/tg-web:snapshot
    container_name: tg-web-test
    restart: unless-stopped
    environment:
      - BACKEND_URL=http://tg-app-test:8080
      - VIRTUAL_HOST=${VIRTUAL_HOST_TEST}
      - LETSENCRYPT_HOST=${VIRTUAL_HOST_TEST}
    networks:
      - nginx-proxy-network

networks:
  nginx-proxy-network:
    external: true