services:
  tg-app-test:
    image: feurle/tg-app:snapshot
    container_name: tg-app-test
    restart: unless-stopped
    expose:
      - "8080"
    environment:
      - SPRING_PROFILES_ACTIVE=stage
      - DB_HOST=tg-database
      - DB_NAME=tg-database-test
      - SMTP_HOST=localhost
      - SMTP_USERNAME=username
      - SMTP_PASSWORD=password
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - SERVICE_BASE_URL=http://tg-app-test:8080
    networks:
      - nginx-proxy-network

  tg-web-test:
    image: feurle/tg-web:snapshot
    container_name: tg-web-test
    restart: unless-stopped
    environment:
      - BACKEND_URL=http://tg-app-test:8080
      - VIRTUAL_HOST=test.tier-gesund.at
      - LETSENCRYPT_HOST=test.tier-gesund.at
    networks:
      - nginx-proxy-network

networks:
  nginx-proxy-network:
    external: true